# Generated by Django 5.0.3 on 2024-03-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ustawienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolor', models.CharField(default='#FFFFFF', max_length=7)),
                ('tytul', models.CharField(default='Moja Strona', max_length=100)),
            ],
        ),
    ]


#SIEMA SIEMA dfs